### ISSUE TITLE
how to use the Right-hand model

### ISSUE THREAD

**Issue by huangfuts** [CalciferZh/minimal-hand#11]
In config.py, I set OFFICIAL_MANO_PATH to the **right** hand model and Run python prepare_mano.py.Then I can get the converted MANO model about right hand. But when I use the converted MANO model about right hand, the result is so bad. Where are the wrongs?
Thus, I want to known how to use the MANO model about right hand OR how to convert the MANO model about right hand?
looking forward to your reply! Thanks a lot.

**Comment by CalciferZh** [comment]
The model is designed for the left hand only. You should flip the image first and then flip the output mesh along x-axis for a right hand.

**Comment by huangfuts** [comment]
> The model is designed for the left hand only. You should flip the image first and then flip the output mesh along x-axis for a right hand.

Thanks for your reply! 
In the project, your code is for the right hand, in which the input has been flipped internally, but where does the output mesh been flipped along x-axis for a right hand? I'm confused very much.

In other words, if i want to put my **left** hand in front of the camera, how should i do? which codes needed to be changed?

looking forward to your reply! Thanks a lot.

**Comment by CalciferZh** [comment]
Simply remove [this line](https://github.com/CalciferZh/minimal-hand/blob/master/app.py#L85) should work.

**Comment by CalciferZh** [comment]
Simply remove [this line](https://github.com/CalciferZh/minimal-hand/blob/master/app.py#L85) should work.

**Comment by huangfuts** [comment]
> Simply remove [this line](https://github.com/CalciferZh/minimal-hand/blob/master/app.py#L85) should work.

yes, I do that. but the displayed rendering-3D hand is inverse！

**Comment by pablovela5620** [comment]
@huangfuts along with flipping the image you need to flip the hand mesh, just multiply the verts by np.array([[-1,0,0], [0,1,0], [0,0,1]]) to reflect over the x-axies

**Comment by pablovela5620** [comment]
@CalciferZh I have a couple of follow up questions regarding the right-hand mesh

1. Did your team train a model for the right hand at all? If so would you be willing to release these models?
2. Is there a major difference between the left-hand mesh and right-hand mesh other than just reflected verts? 
3. I would understand if DetNet only works with left-handed images but does IKNet allow for using the right-hand mesh? If not how would one go about getting the quaternions needed to pose the mesh rather than just reflecting the mesh without needing to train a new IKNet

**Comment by CalciferZh** [comment]
1. No. Everything is for the left hand only.
2. I think it's only about flipping.
3. The DetNet and the IKNet are both for the left hand only. For the right hand, the image needs to be flipped and processed as if it is the left hand, and the output is also a left hand. Then you can flipped it back to be a right hand.

**Comment by pablovela5620** [comment]
This is my ignorance on quaternion math but would the best way to flip is just to convert to axis angle form and subtract 180deg? I'm guessing there's a similar operation for quaternions but I'm don't know it.

**Comment by huangfuts** [comment]
> @huangfuts along with flipping the image you need to flip the hand mesh, just multiply the verts by
> `np.array([[-1,0,0], [0,1,0], [0,0,1]])` to reflect over the x-axies

the question has been solved. Thanks  very much!
Good luck to you!

**Comment by CalciferZh** [comment]
> This is my ignorance on quaternion math but would the best way to flip is just to convert to axis angle form and subtract 180deg? I'm guessing there's a similar operation for quaternions but I'm don't know it.

You don't really need to deal with quaternion flipping. You can apply the "left quaternions" to the left hand model, and then flip the mesh/joint coordinates to get the corresponding right hand.

By definition, the rotation along axis u with angle a can be written in quaternion as (cos(a/2), u * sin(a/2)). Therefore, to flip along some axis, you can directly operate the last three components the the quaternion.

**Comment by pablovela5620** [comment]
gotcha, the reason I'm asking is that I want to rig my own model using the kinematic tree and joint positions/rotations. Flipping the mesh/joints won't really help if I am using a completely different set of verts/faces based on the kinematic skeleton the requires the joint rotations for a right hand rather than just the left hand.

**Comment by Bob130** [comment]
@pablovela5620  Did you solve the flip problem for quaternion? I try to multiply the third (y) and fourth (z) elements of quaternion by -1, but it doesn't work for right hand. Thank you in advance if you can give me some advice.
