### ISSUE TITLE
Hand croppping?

### ISSUE THREAD

**Issue by pablovela5620** [CalciferZh/minimal-hand#13]
Was DetNet trained on cropped hand images? or did you use the full image? I'm a bit confused since it seems in the inference app there's zero hand cropping. It looks like all that is done is the image is converted to a square and then reshaped to 128x128. 

From what I can tell most hand keypoint detection pipelines usually involve first cropping out the hand and then feeding it into the 2D/3D keypoint detector.

**Comment by CalciferZh** [comment]
It's trained on the cropped images. However, during training, the scale and the offset of the cropping is intentionally strongly randomized, so that as long as the hand is neither too small nor too large, the model always works fine.

**Comment by pablovela5620** [comment]
Gotcha, so in this repo you're doing zero hand cropping (no hand detection pipeline) meaning that if you were to include a hand object detector one could expect better accuracy?

**Comment by CalciferZh** [comment]
In theory, yes :)
