### ISSUE TITLE
Output probability

### ISSUE THREAD

**Issue by ttdd11** [CalciferZh/minimal-hand#14]
Cool repo. I am wondering if it's possible to also output to per joint probability. Is that something that you have looked into?

**Comment by CalciferZh** [comment]
You can view the maximum value of the heat map as the confidence, which is always between [0, 1]. We also thought about a more explicit formulation for confidence, but didn't get a good answer.

**Comment by ttdd11** [comment]
How do I extract this confidence for the heatmap?

**Comment by ttdd11** [comment]
Solved thank for your help.
