### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by ttdd11** [CalciferZh/minimal-hand#15]
I'm wondering how you would go about changing the the batch size of detnet? I've tried a few thing but am unable to load your pretrained weights unless the batch size is 1. Thanks again for your help.

**Comment by CalciferZh** [comment]
The model itself supports any batch. If you want to change the batch size, you need to implement the wrapper yourself, which means defining the placeholder, feeding it into the network function, and retrieving the coordinates/angles on your own. The wrapper provided in the released code would no longer work.
