### ISSUE TITLE
[Plan on PyTorch?]

### ISSUE THREAD

**Issue by AlexHu123** [CalciferZh/minimal-hand#16]
Thanks for your great work!
Would you have a plan for releasing PyTorch version?

**Comment by CalciferZh** [comment]
No we won't.

**Comment by MengHao666** [comment]
> Thanks for your great work!
> Would you have a plan for releasing PyTorch version?

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
