### ISSUE TITLE
Any plan to release train code?

### ISSUE THREAD

**Issue by z13974509906** [CalciferZh/minimal-hand#18]
Is there a schedule?

**Comment by CalciferZh** [comment]
https://github.com/CalciferZh/minimal-hand/issues/2

We are working on that, but it takes much longer time than releasing the model only. We are not sure when we can release it yet.

**Comment by MengHao666** [comment]
> Is there a schedule?

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
