### ISSUE TITLE
About the training

### ISSUE THREAD

**Issue by DanielMao2015** [CalciferZh/minimal-hand#2]
Hey, it is a very cool work. By the way, is there any plan for releasing the training code and dataset?

**Comment by CalciferZh** [comment]
Hi, the detection model is trained with following datasets:
* [CMU HandDB](http://domedb.perception.cs.cmu.edu/handdb.html)
* [Rendered Handpose Dataset](https://lmb.informatik.uni-freiburg.de/resources/datasets/RenderedHandposeDataset.en.html)
* [GANerated Hands Dataset](https://handtracker.mpi-inf.mpg.de/projects/GANeratedHands/GANeratedDataset.htm)

The IK model is trained with the poses shipped with [MANO](https://mano.is.tue.mpg.de/).

Please check our paper for more details.

About the training code, it's too messy and we are trying to clean it out. But don't expect it to be released in a short time.

Good luck :)

**Comment by pablovela5620** [comment]
Would love to see the training code even if it takes a bit of time!

**Comment by AlexHu123** [comment]
Would love to see the training code even if it takes a bit of time!

**Comment by MengHao666** [comment]
> Hey, it is a very cool work. By the way, is there any plan for releasing the training code and dataset?

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
