### ISSUE TITLE
Is my results normal?

### ISSUE THREAD

**Issue by vinnik-dmitry07** [CalciferZh/minimal-hand#21]
https://youtu.be/RbReWo94W68
I use the example app. Did I miss some additional setups?

**Comment by CalciferZh** [comment]
![test_3](https://user-images.githubusercontent.com/20183700/81759308-edc1fb00-94f6-11ea-947d-3db0b13b1bbd.PNG)
![test_1](https://user-images.githubusercontent.com/20183700/81759324-f87c9000-94f6-11ea-98de-a9fe9db31438.PNG)
![test_2](https://user-images.githubusercontent.com/20183700/81759328-fadeea00-94f6-11ea-882c-28c9ee92a24d.PNG)

Just made a quick test at home. We found that the IK part sometimes "smoothes" the pose. You may consider using the keypoint prediction only, if you don't really need the mesh.
