### ISSUE TITLE
How do you get the output for 'Results on Sequences from Internet'?

### ISSUE THREAD

**Issue by cbsudux** [CalciferZh/minimal-hand#22]
In your video, I see that you detect hands on the first frame and crop. Couple of questions:  
1) What model do you use to crop?
2) You mention that you use 2D pose for the rest of the frames. I don't understand this, can you elaborate please?

Thanks

**Comment by CalciferZh** [comment]
1. in the video we annotate the first bbox manually
2. the bbox can be updated with the 2D predictions for each frame

**Comment by cbsudux** [comment]
Okay thanks
