### ISSUE TITLE
About 3D label

### ISSUE THREAD

**Issue by www516717402** [CalciferZh/minimal-hand#23]
Thank you for great project. In your project set Batch*num_points*W*H*3 as 3d label. I want to know how to generate 3D label ? Anyone can help me.

**Comment by CalciferZh** [comment]
By tiling the GT coordinates. Each pixel would have the same value across the map.

**Comment by www516717402** [comment]
@CalciferZh Thanks for reply. I see detail in your paper city.

**Comment by liwenssss** [comment]
> @CalciferZh Thanks for reply. I see detail in your paper city.

hi, it seems that you know how to generate location map mentioned in the paper, can you tell me more details by some simple code?

**Comment by www516717402** [comment]
@liwenssss Please see paper **Sec3.1 3D Detector**.

**Comment by liwenssss** [comment]
> @liwenssss Please see paper **Sec3.1 3D Detector**.

you means that each gt location map has only one same value?
