### ISSUE TITLE
Getting bad results on simple poses. Any idea why?

### ISSUE THREAD

**Issue by cbsudux** [CalciferZh/minimal-hand#25]
I'm using the left hand model and have flipped it accordingly. 
- Also when I bend one finger, the model doesn't recognize this. 

![Screenshot from 2020-05-16 01-29-17](https://user-images.githubusercontent.com/8793690/82091724-846c0300-9715-11ea-9387-4237d096a3eb.png)
![Screenshot from 2020-05-16 01-30-01](https://user-images.githubusercontent.com/8793690/82091735-8930b700-9715-11ea-8859-e336a60253a4.png)
![Screenshot from 2020-05-16 01-30-34](https://user-images.githubusercontent.com/8793690/82091740-8b931100-9715-11ea-9906-3f499636a01b.png)

**Comment by CalciferZh** [comment]
We also found that the model may fail on some "simple" cases. We think that's because such images were not presented in the training data. We are working on v2 to fix such problems.

**Comment by cbsudux** [comment]
Any ideas on why this happens? I'm confused since these are very similar to the input on the [teaser.gif](https://github.com/CalciferZh/minimal-hand/blob/master/teaser.gif) and this [issue](https://github.com/CalciferZh/minimal-hand/issues/21). 

What cases does your model work well then?

**Comment by CalciferZh** [comment]
I'm not sure if you are using it correctly, as the result seems weird to me. We've presented many cases in the video where the model works fine.

**Comment by cbsudux** [comment]
Okay
