### ISSUE TITLE
Joints visualization of demo video.

### ISSUE THREAD

**Issue by dihuangdh** [CalciferZh/minimal-hand#26]
Hi, Yuxiao

Thanks for your awesome work!

In the demo video, you plot joints like this: 

![Screenshot from 2020-05-26 20-40-20](https://user-images.githubusercontent.com/57213566/82901901-34046900-9f91-11ea-9842-307e9aa3c927.png)

How to align joints with image?

Thanks.

@CalciferZh

**Comment by CalciferZh** [comment]
That's 2D prediction.
