### ISSUE TITLE
Training step

### ISSUE THREAD

**Issue by www516717402** [CalciferZh/minimal-hand#28]
Hello. 
About DetNet training. 2D points / 3D points / delta map by  One-time training, or Train in order?
In my code training 2D points and 3D points in FreiHand by One-time. However get terrible result.
Hope your reply.

**Comment by CalciferZh** [comment]
Yes it's one time. In our experiments it's quite easy to converge.

**Comment by www516717402** [comment]
In your paper use CMU dataset. It has 2D keypoints, with out 3D infomation. How to train one time?

**Comment by CalciferZh** [comment]
We set the weight of 3D losses to zero for the samples without annotations

**Comment by MengHao666** [comment]
> In your paper use CMU dataset. It has 2D keypoints, with out 3D infomation. How to train one time?

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
