### ISSUE TITLE
How to extract 3d coordinates

### ISSUE THREAD

**Issue by lucas-amin** [CalciferZh/minimal-hand#29]
Hello! First of all, thank you for this project, it is awesome!

Please, how can I extract 3d coordinates of each joint? What is the distance unit? Is it possible to extract the hand pose into a file?

Thank you.

**Comment by CalciferZh** [comment]
`wrappers.ModelDet` can be used to extract 3D coordinates from the input image.
The length of the output is normalized by the length of the reference bone, which is roughly 75mm on average. It's impossible to get the accurate absolute value.

**Comment by RohitSingh1226** [comment]
Input image? Can we not print the coordinate live time?
