### ISSUE TITLE
'NoneType' object has no attribute 'load_from_json'

### ISSUE THREAD

**Issue by visonpon** [CalciferZh/minimal-hand#3]
Hi, @CalciferZh , thanks for releasing this wonderful work, but when test on my own images I got an error like above, can you give some advice?
btw, after succefully installed all requirements , there is also an `GLFW Error: X11: The DISPLAY environment variable is missing Failed to initialize GLFW` 
Hope can receive your response, thanks~

**Comment by CalciferZh** [comment]
As the error suggests, that's because your environment failed to init GLFW for some reason, which is required by `open3d` for visualization. You can still use the model without this visualization.
