### ISSUE TITLE
Can you tell me how to visualize a bounding box of the scene?

### ISSUE THREAD

**Issue by li2508264** [CalciferZh/minimal-hand#31]
like your demo the black and white grid,thanks

**Comment by CalciferZh** [comment]
It's not a bounding box but only a simple "ground" to make the visualization looks better. We draw a large rectangle with such texture using OpenGL and place it there.

**Comment by www516717402** [comment]
Great! Just solved my problem. Thank you much.

**Comment by li2508264** [comment]
thanks a lot.
