### ISSUE TITLE
when will training code release?

### ISSUE THREAD

**Issue by jinfagang** [CalciferZh/minimal-hand#32]
When will release the training code?

**Comment by CalciferZh** [comment]
Thank you for your interest. It depends. Now we have other students working on this, and personally I'm sure when it will be ready.

**Comment by MengHao666** [comment]
> When will release the training code?

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
