### ISSUE TITLE
Obtaining MoCAP from a two hand video dataset

### ISSUE THREAD

**Issue by Linardos** [CalciferZh/minimal-hand#33]
Greetings and many thanks for the great work.

I wanted to utilize your code to extract MoCAP data given a first person RGB video dataset that has a clear view of both hands during a task. Given that your model is restricted to predicting from a single hand I wonder whether it will consistently show preference for the left hand if presented with videos that display both? If that's the case I suppose I could parse the dataset twice, flipping it the second time to obtain both hands' coordinates, right?

**Comment by CalciferZh** [comment]
Thanks for your question.
The model has never seen any image with both hands presented. It's hard to say if it would work well in such cases.
If the two hands are always distant from each other, a walk-around is to crop each frame with the bounding box of only one hand before feeding into the model, and keep updating the bbox with the 2D predictions, as we did in the demo video ("in-the-wild" section).
If there are hand-hand interactions, the model may fail. We also demonstrated such cases in the video ("fail cases" section).

**Comment by Linardos** [comment]
Ah I see now. However, in the fail case you present the journalist's fingers interlay each other or there is a large fast motion. When performing tasks, the hands might get close but not that close unless they squeeze something and likely never be too fast as tasks tend to be delicate for such gestures. 

Might you have the code with which you constructed these cases somewhere? The code to do the bounding box, cropping and prediction I mean. I really believe it will be of great use to me.

**Comment by CalciferZh** [comment]
Sorry we don't have the code off-the-shell. It shouldn't be difficult to implement. You can get the the 2D predictions from the released code in `wrappers.py`, and then just compute the bounding box according to the joint locations.

**Comment by Linardos** [comment]
Ah that's fine then, I will figure it out. Thank you kindly for your speedy replies mate. I'll be closing this issue for now.

**Comment by Linardos** [comment]
Sorry, I just realized, you mentioned that I can "get the 2D predictions from the released code in wrappers.py, and then just compute the bounding box according to the joint locations." Doesn't that imply that I will run a prediction on the frame beforehand? So if it's two hands how can I be sure it won't get confused if I don't have the bounding box in place already?

**Comment by CalciferZh** [comment]
I would suggest to manually annotate the bounding box of the first frame and then keep tracking it (that's what we did in the demo video). Otherwise it would be a bit more difficult, and I'm not sure how well the model would perform. Distinguishing two hands in the same image is still an open question.
