### ISSUE TITLE
Could you add some new features

### ISSUE THREAD

**Issue by DerDennisOP** [CalciferZh/minimal-hand#34]
I'll write it succinctly

Nice futures:

- Two Hands at the same time
- Training class, where u can train your own dataset - with an training exsample
and
- Hand Positional Tracking (Not only relative position)

Some solutions:
Adding a handfinder and putting this into the ai, then calculating the relative position with the center of the rect

best regards,
DENNIS

**Comment by CalciferZh** [comment]
Thank you for your suggestion. I'll consider when I have time.
