### ISSUE TITLE
Why not use the ImageNet pretrained model as initialization as described in paper?

### ISSUE THREAD

**Issue by wangzheallen** [CalciferZh/minimal-hand#4]

**Comment by wangzheallen** [comment]
Instead, in the paper author uses  Xavier initialization

**Comment by CalciferZh** [comment]
We agree with https://arxiv.org/abs/1811.08883 that the help of ImageNet pre-training would be limited. Also, ImageNet is too different with our task.

**Comment by wangzheallen** [comment]
> We agree with https://arxiv.org/abs/1811.08883 that the help of ImageNet pre-training would be limited. Also, ImageNet is too different with our task.

Thanks for the answer, it will be good to see a comparison version with ImageNet pre-trained model. :)

**Comment by CalciferZh** [comment]
We will consider :)
