### ISSUE TITLE
Finding the centroid of the hand

### ISSUE THREAD

**Issue by RohitSingh1226** [CalciferZh/minimal-hand#45]
Can we get the centroid or is there a link in the middle to roughly estimate the centroid

**Comment by CalciferZh** [comment]
No it's not provided in the model.

**Comment by RohitSingh1226** [comment]
Printing the position of the middle fingers bottom link is possible?

Also I am getting low fps when  I am running, what are you using it to compile on gpu
It is no where near 100fps 
I use 1660Ti nvidia

**Comment by RohitSingh1226** [comment]
@CalciferZh pls help, I reinstalled CUDA10 and cudnn and used only tensorflow-gpu==1.14.0. TFhas no variable scope 
and several errors in wrappers.py

**Comment by CalciferZh** [comment]
> Printing the position of the middle fingers bottom link is possible?
> 
> Also I am getting low fps when I am running, what are you using it to compile on gpu
> It is no where near 100fps
> I use 1660Ti nvidia

You can manually annotate the vertex index of the mesh and then print it.
100 fps is the pure runtime tested on 1080ti. Reading frames from the camera, rendering, etc. may also take some time which is accounted.

**Comment by CalciferZh** [comment]
> @CalciferZh pls help, I reinstalled CUDA10 and cudnn and used only tensorflow-gpu==1.14.0. TFhas no variable scope
> and several errors in wrappers.py

I'm sorry but I'm not an expert in tensorflow. I cannot help much on the environmental issues.
