### ISSUE TITLE
Suggestion for extracting 3D keypoints for both hands

### ISSUE THREAD

**Issue by ujjawalcse** [CalciferZh/minimal-hand#46]
Hi @CalciferZh ,
Thanks for this elaborative and easy-to-use repository. I tried your code and it's working fine for the right hand as you said (flipped internally as the model here is trained for left hand).
I went one step forward and tried to detect both hands in realtime and used your "ModelDet()" from "wrappers.py" to get xyz for every bounding boxes generated by hand-detection model. 
My confusion is that how can i distinguish both hands(left or right) to get the corresponding results from your model.
Please share here if anyone has done the same.

**Comment by AlbertoSabater** [comment]
Hi! Have you found a solution for extracting 3D keypoints of both hands?
Thanks in advance!

**Comment by CalciferZh** [comment]
Hi guys, this paper might be helpful to you: https://handtracker.mpi-inf.mpg.de/projects/RGB2Hands/
