### ISSUE TITLE
Could you supply me with train code?

### ISSUE THREAD

**Issue by Wu-Jintao** [CalciferZh/minimal-hand#48]
I am very interesting in your work and want to follow your work. I don't Know whether you could provide train code to me.

Hope for your reply.
Best
Wu

**Comment by MengHao666** [comment]
> I am very interesting in your work and want to follow your work. I don't Know whether you could provide train code to me.
> 
> Hope for your reply.
> Best
> Wu

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
