### ISSUE TITLE
Is there some ways to update the model?

### ISSUE THREAD

**Issue by JuliaJiaYou** [CalciferZh/minimal-hand#49]
Hi, thanks for sharing. I am also working on HGR, and I want to do some modifications for my product. I do not need to reconstruct the hand model using MANO, I just want to classify different gestures from skeleton. But seems your models are pretrained. Are there some methods to modify your pretrained model, or just retrain it?
Thanks!!!

**Comment by CalciferZh** [comment]
I guess you can extract the weights from the pretrained model as an initialization to train your own model, e.g. adding a few fully connected layers to predict gesture category from joint positions.

**Comment by JuliaJiaYou** [comment]
Thanks！ I will try this!
