### ISSUE TITLE
Have you tried another rotation representation? and how is axis-angle performed in your paper?

### ISSUE THREAD

**Issue by wangzheallen** [CalciferZh/minimal-hand#5]
https://arxiv.org/abs/1812.07035 which is also used in VIBE and SPIN.

Thanks!

**Comment by CalciferZh** [comment]
As quaternions works well in our experiments, we want to avoid any unnecessary design to keep things "minimal". The 6D representation may improves the result in number, but probably won't change things substantially. The axis-angle representation works way worse in the preliminary experiments, so we just abandon it.

**Comment by wangzheallen** [comment]
> As quaternions works well in our experiments, we want to avoid any unnecessary design to keep things "minimal". The 6D representation may improves the result in number, but probably won't change things substantially. The axis-angle representation works way worse in the preliminary experiments, so we just abandon it.

Thanks!
