### ISSUE TITLE
IK using 3D joint coordinates

### ISSUE THREAD

**Issue by Amebradi** [CalciferZh/minimal-hand#52]
Hello, 
First, I would like to congrats you on the amazing paper. Moreover, I have a question regarding IK architecture. I would like to know if there is any comparison between the IK architecture that you proposed here and the other algorithm that you previously proposed based on Levenberg-Marquadr on Mano's hand. Additionally, could you guide me on applying the IK architecture without running the entire code as I have some ground truth 3d coordinates, and I want to obtain the IK parameters? Thanks a lot.

**Comment by CalciferZh** [comment]
I don't have a comparison on hand. But the LM based solver could not handle global rotation, so I would guess the network based approach should always be better.
The IK part you can check https://github.com/CalciferZh/minimal-hand/blob/master/wrappers.py#L73   
https://github.com/CalciferZh/minimal-hand/blob/master/wrappers.py#L167   illustrates how to pre-process the input data

**Comment by Amebradi** [comment]
Thanks a lot for the guidance. For my final question, I was wondering if you could possibly guide me on any IK gold-standard method that I can use to make a comparison with the results calculated based on this study and a gold-standard method. Thanks

**Comment by CalciferZh** [comment]
I think it's hard. Typically IK is done with iterative optimization, and the core is how to define the objective function and how to optimize it.
Each work would propose its own energy function - sometimes the energy function can be the main contribution. The optimization algorithm can be also very complex that a good linear approximation can also be listed as contribution of one paper.
Therefore, it is really hard to name a gold-standard. There is only the simplest or naivest approach, which usually does not work well unfortunately.

**Comment by Amebradi** [comment]
Thanks a lot for the clarification. It was super helpful. But could you please help me to understand for IK, why not directly measure the Angeles as we have all of the 3D joint coordinates (closed-loop). In this way we don't need to have iterative optimization. Thanks again

**Comment by CalciferZh** [comment]
Because it's not a closed-loop :)
When you have a lot of accurate keypoints, it is; but usually we only have a few keypoints which are not completely reliable, so it is not.
