### ISSUE TITLE
About location map

### ISSUE THREAD

**Issue by qiufeng1994** [CalciferZh/minimal-hand#53]
hello, I have read the paper and the code. But I am still confused about how to get the GT location maps from 2d heatmaps.  Could you explain it in more detail? Thanks a lot!

**Comment by CalciferZh** [comment]
Maybe you could check the code here: https://github.com/CalciferZh/minimal-hand/blob/master/wrappers.py#L39

**Comment by MengHao666** [comment]
> hello, I have read the paper and the code. But I am still confused about how to get the GT location maps from 2d heatmaps. Could you explain it in more detail? Thanks a lot!

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
