### ISSUE TITLE
How can I overlay the mesh result on the origin image as Figure 1 in the paper ?

### ISSUE THREAD

**Issue by liulj13** [CalciferZh/minimal-hand#54]
Hi, I noticed that the rendered result is not the same size as the input image, and it is very difficult to align them in the same image. I wonder how you create the visualization result as show in Figure 1 in your paper? Thank you!
![image](https://user-images.githubusercontent.com/14155544/97129328-8aace380-1779-11eb-9184-44d171b440b9.png)

**Comment by CalciferZh** [comment]
I think the easiest way is to use cv2.solvePnP to solve for camera RT that best aligns 3D and 2D predictions, and then do the rendering with the camera parameters. You can further have a procrustes alignment in the 2D plane for a better overlay.
This is not how we did in the paper, but we realized later that this is possibly the simplest approach.
