### ISSUE TITLE
Global joint keypoints!

### ISSUE THREAD

**Issue by AlbertoSabater** [CalciferZh/minimal-hand#56]
Hi! Congratulations foryour project, it's awesome.

I am trying to use minimal-hand to extract hand joint coordinates. As seen in your code, you normalize them and calculate coordinates relative to M0 joint.
Is there any way to extract the coordinates relative to the world/frame? Here, if the hand is moving to one side or to the background/front, it should be represented by the coordinates. The normalized ones does not reflect this motion.

Thanks in advance!

**Comment by CalciferZh** [comment]
To some extent, this is mathematically impossible due to the depth-scale ambiguity of monocular approaches. We briefly discuss this in Sec 3.1: Global Translation. Hope this can be helpful.
