### ISSUE TITLE
question about the get_pose_tile module in detnet

### ISSUE THREAD

**Issue by nsl2014fm** [CalciferZh/minimal-hand#57]
I'm confused about the ‘get_pose_tile’ module in the detnet. What is the purpose of it.

`def detnet(img, n_stack, training):
  features = resnet50(img, 'resnet', training)
  pos_tile = get_pose_tile(tf.shape(img)[0])
  features = tf.concat([features, pos_tile], -1)`

`def get_pose_tile(N):
  pos_tile = tf.tile(
    tf.constant(
      np.expand_dims(
        np.stack(
          [
            np.tile(np.linspace(-1, 1, 32).reshape([1, 32]), [32, 1]),
            np.tile(np.linspace(-1, 1, 32).reshape([32, 1]), [1, 32])
          ], -1
        ), 0
      ), dtype=tf.float32
    ), [N, 1, 1, 1]
  )
  return pos_tile`

**Comment by CalciferZh** [comment]
It's some legacy code the can be ignored. We found it's not helpful in the later experiments.
