### ISSUE TITLE
question about backbone 

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#58]
Hi,
First thanks for such great work!
I am curious about the usage of Resnet50  as the backbone.
I saw you changed a lot compared with the original offical implementation of Resnet50.
And I saw in many previous works like [handobjectconsist](https://github.com/hassony2/handobjectconsist) and [obman_train](https://github.com/hassony2/obman_train), they used the pretrained resnet model on ImageNet and only abandoned last fully connected layer.
So I wonder if you ever found any improvements using your modified resnet compared with the pretrained model.
Could u give any detailed explaination about it?
Hope for your generous reply, thanks!

**Comment by CalciferZh** [comment]
Hi, thanks for your interest.
Actually we do not have a specific reason for that.
Maybe a pretrained resnet could give better quantitative results, but that's not we are pursuing for, and that won't change things substantially. We would be very happy to see a better model with a different backbone, or with better tuned hyperparameters :)

**Comment by MengHao666** [comment]
Thanks , got it !
