### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by slava-smirnov** [CalciferZh/minimal-hand#59]
hey! great work! any updates on training code to be publicly available?

**Comment by CalciferZh** [comment]
Hi, thanks for the interest. I've moved to a new project for a long time. Someone else in my group is working on releasing the training code. I don't know his progress. Seems that it's quite slow.
On the other hand, it should not be difficult to implement the training. I'm open to discuss any issues during the implementation.

**Comment by MengHao666** [comment]
> hey! great work! any updates on training code to be publicly available?

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
