### ISSUE TITLE
question about need_norm and norm

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#60]
Hi ,there are two things confusing me.

1. One is need_norm, what is it used for?
`            if need_norm:
                dmap_norm = tf.norm(dmap_raw, axis=-1, keepdims=True)
                dmap = dmap_raw / tf.maximum(dmap_norm, 1e-6)
            else:
                dmap = dmap_raw`

2. the other is in which you define the iknet:
`eps = np.finfo(np.float32).eps
    norm = tf.maximum(tf.norm(theta_raw, axis=-1, keepdims=True), eps)
    theta_pos = theta_raw / norm`
in this way, u believe the reference bone mentioned in your paper is the longest bone ,and u used its length to normalize bone vectors.Is that always true?

**Comment by CalciferZh** [comment]
1. It's merely length normalization.
2. I don't get your point. `maximum` is to avoid numerical issues.
