### ISSUE TITLE
By tiling the GT coordinates. Each pixel would have the same value across the map.

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#61]
By tiling the GT coordinates. Each pixel would have the same value across the map.

_Originally posted by @CalciferZh in https://github.com/CalciferZh/minimal-hand/issues/23#issuecomment-629286585_

**Comment by MengHao666** [comment]
@CalciferZh 
Hi, I am trying to implement your awesome project using Pytorcch and I am quite confused about how to generate 3D lables to train DetNet.
In your paper, u said 

> Ground truth location maps LGT and delta maps DGT are
constructed by tiling the coordinates of the ground truth
joint position and bone direction to the size of the heat
maps. 

,

> Ground truth location maps LGT and delta maps DGT are
constructed by tiling the coordinates of the ground truth
joint position and bone direction to the size of the heat
maps. Since we are mainly interested in the 3D predictions
at the maxima of the heat maps, the difference is weighted
with HGT, where is the element-wise matrix product.

,

> The location maps L and the delta maps
D are supervised by 3D annotations. During inference, the
3D position of joint j can be retrieved by a simple look-up
in the location map Lj at the uv-coordinate corresponding
to the maxima of the heat map Hj. 

and

> To alleviate the fundamental depth-scale ambiguity in the monocular setting, the
predicted coordinates are relative to a root joint and normalized by the length of a reference bone. We select the middle
metacarpophalangeal to be the root joint, and the bone from
this joint to the wrist is defined as the reference bone.

And I found the size of **delta_map** and **location_map** are all  **(1, 32, 32, 21, 3)**, 
so in my own understanding, we can get the relative and normalized 3D handjoints **(21,3)**, 
so it is easy to generate orrresponding **groundtruth delta (21,3)** and **ground location (21,3)**

And obviously, in training process, u inference the **predicted delta(21*3)** and **predicted location(21*3)** by looking up realted loaction from 2D heatmap.

So here comes the two choices during training:
1. you can only caculate the loss between the predcited delta and groundtruth delta. so as location.

2. like how u deal with 2D prediction, you can also generate ground truth heatmap. and calculate the whole loss between two heatmaps.

I was deeply confused that which one u uesd, as u describe **"Each pixel would have the same value across the map."** and u aslo mention **u used a product loss**  to take care only about the location corresponding to 2D heatmaps to reduce caculations.
And what is the point if u only caculate the loss in locations related to 2D heatmap and genrate a full groundtruth delta_maps and location maps with one same value (21*3---->1*32*32*21*3). It is so redundant.

And what do u mean by  **tiling the GT coordinates**? It seems that u construct a new uv cooridinate in cropped img(128*128*3),and I think transfering GT cooridinates to relative and normalized cooridiante is enough.
what is the "tiling", and how do u implement it ?

**Comment by CalciferZh** [comment]
This formulation is first proposed by the VNECT paper. Maybe you could check the paper to see more detailed explanations on this redundancy.
Tiling means `np.tile` or `tf.tile`.
