### ISSUE TITLE
How to get beta in IKNet?

### ISSUE THREAD

**Issue by Mrsirovo** [CalciferZh/minimal-hand#63]
You have done really a great work!

When I read your paper about, I am a little confused about how to find the best beta in IKNet by minimizing E(beta).
Is beta directly got by solving the function? Or using ML methods like Newton down-hill method?

Thank you
Best wishes

**Comment by CalciferZh** [comment]
Hi, thanks for the interest. We use a LM solver to estimate the beta.

**Comment by Mrsirovo** [comment]
Thanks a lot!
By the way, would you mind telling me where is the code about the LM solver in the project?
I have been stuck for a long time.
Or is there any recommended code about LM solver?
@CalciferZh

**Comment by CalciferZh** [comment]
We did not release the shape estimation part in this repository, as we want to keep this project "minimal".
In [this project](https://github.com/CalciferZh/Minimal-IK) we have a LM solver. Maybe you can take a look :)

**Comment by Mrsirovo** [comment]
I think I have found it.

`params_est = solver.solve(wrapper, keypoints)`

This params_est refers to beta, and the solver.solve is the LM solver.
Do I get the right answer?

**Comment by CalciferZh** [comment]
Not exactly. That project is used to solve theta. You can modify it to solve beta.

**Comment by Mrsirovo** [comment]
Thanks a lot!
