### ISSUE TITLE
the implementation of location map loss and delta map loss

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#64]
Hi， thanks for your great work.

I found in wrappers.py ,  the size of location map and delta map are equally 1X32X32X21X3,
and the size of 2D heatmap is 1X32X32X21,
but the loss is caculated as follows in you paper 
![1](https://user-images.githubusercontent.com/47114466/100058994-48a0bb80-2e65-11eb-9903-ba9b9a466857.png)

But I am quite confused how to do "element-wise matrix product " between variables with size of 1x32X32X21X3 and  1X32X32X21 respectively. Could u give more details?

**Comment by CalciferZh** [comment]
It's done for each channel of D.

**Comment by MengHao666** [comment]
> It's done for each channel of D.

Do u mean first transfer 1X32X32X21 to 1X32X32X21X3 first using tile ?

**Comment by CalciferZh** [comment]
yes

**Comment by MengHao666** [comment]
thanks
