### ISSUE TITLE
About  effect of dexter+object dataset

### ISSUE THREAD

**Issue by miooooooooooo** [CalciferZh/minimal-hand#65]
When I test the video sequence about the grasp pose in dexter+object, I find the output 3D hand is shaking drastically, is there normal

**Comment by miooooooooooo** [comment]
And I have tested your teaser.gif data, but the same phenomenon occurs, and it looks very different from your result.

**Comment by CalciferZh** [comment]
For visualization, we used a [temporal filter](https://cristal.univ-lille.fr/~casiez/1euro/) for better smoothness.

**Comment by MengHao666** [comment]
> And I have tested your teaser.gif data, but the same phenomenon occurs, and it looks very different from your result.

Hi, do you know how to evaluate in DO and EO dataset? I don't know how to do global alignment for these 2 datasets.
