### ISSUE TITLE
When optimizing beta, is theta fixed?

### ISSUE THREAD

**Issue by Mrsirovo** [CalciferZh/minimal-hand#67]
Hi, I meet another question.

When I get into manopth, I find that theta affects length of bones though beta is fixed.
So I want to know that is theta fixed when using LM to optimizing beta in the IKNet?
And when calculate quaternion, is beta fixed as well?

Thanks in advance.

**Comment by CalciferZh** [comment]
Beta is only about shape, which is only about bone lengths. Therefore, you can first optimize beta to best match the bone lengths without bothering theta, and then fix beta and only estimate theta.
