### ISSUE TITLE
Train code

### ISSUE THREAD

**Issue by yinyiyu** [CalciferZh/minimal-hand#68]
Thank you for your outstanding work. I hope you can find the time to release the training code.

**Comment by CalciferZh** [comment]
Thanks. I'll try :)

**Comment by MengHao666** [comment]
> Thank you for your outstanding work. I hope you can find the time to release the training code.

I reimplement some parts of this paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. you may check it and find bugs, thanks!
