### ISSUE TITLE
how to do "global alignment"?

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#69]
Hi,I got confused about another problem.

In your paper ,u said "As previous work, we perform a global alignment to better measure the local hand pose. "
How do u implement the "global alignment"? Is it just to transalate the root joint to same location of label (Is the lable here is also root-relative and normalized using reference bone?) I got AUC of 0.1 only using DetNet retrained in RHD.

Could u provide the "prevous work" that do  a global alignment like u? And it would bebetter if their code has been public available.
Thanks!

**Comment by CalciferZh** [comment]
Please refer to this work https://handtracker.mpi-inf.mpg.de/projects/GANeratedHands/

**Comment by MengHao666** [comment]
> Please refer to this work https://handtracker.mpi-inf.mpg.de/projects/GANeratedHands/

Thanks for the generous reply!
I have checked the paper u referred to, but it doesn't mention in details.
Does the global alignment first translates the root joint to the ground truth root location, and then multiplies the rest root-relative joint location with  scale , which make the aligned refrence bone as long as each other ?

And I wrote a small script for it, it would be very kind of u if u can check if it same with yours.



```
        trans = targ[i][root_idx] - pred1[i][root_idx]
        
        ref_bone_pred = np.linalg.norm(pred1[i][0] - pred1[i][9])
        ref_bone_gt = np.linalg.norm(targ[i][0] - targ[i][9])
        scale = ref_bone_gt / ref_bone_pred
        
        pred1_[i] += trans
        for j in range(21):
            pred1_[i][j] = pred1_[i][root_idx] + scale * (pred1_[i][j] - pred1_[i][root_idx])
```

All Best!
Hao

**Comment by CalciferZh** [comment]
> Does the global alignment first translates the root joint to the ground truth root location, and then multiplies the rest root-relative joint location with scale , which make the aligned reference bone as long as each other ?

This reads correct to me. I did not find any obvious problem in the script, either.

**Comment by MengHao666** [comment]
> > Does the global alignment first translates the root joint to the ground truth root location, and then multiplies the rest root-relative joint location with scale , which make the aligned reference bone as long as each other ?
> 
> This reads correct to me. I did not find any obvious problem in the script, either.

Thanks for kind notification.

**Comment by MengHao666** [comment]
> > Does the global alignment first translates the root joint to the ground truth root location, and then multiplies the rest root-relative joint location with scale , which make the aligned reference bone as long as each other ?
> 
> This reads correct to me. I did not find any obvious problem in the script, either.

Hi ,that script seems to work for STB and RHD dataset. 

However, the global alignment for EO and DO seems somewhat equivocal for me. In your Supplemental Document , you referred it as two ways: **depth aligment** and **centeroid aligment**. But I did go through all papers you cited about these 2 ways and could not find any explicit and clear description. And I really don't know how to align 5 predicted finger tips to ground truth. Could u provide scripts about these 2 kinds of alignment?

Thanks.
Hao

**Comment by MengHao666** [comment]
> > Does the global alignment first translates the root joint to the ground truth root location, and then multiplies the rest root-relative joint location with scale , which make the aligned reference bone as long as each other ?
> 
> This reads correct to me. I did not find any obvious problem in the script, either.

Hi ,that script seems to work for STB and RHD dataset. 

However, the global alignment for EO and DO seems somewhat equivocal for me. In your Supplemental Document , you referred it as two ways: **depth aligment** and **centeroid aligment**. But I did go through all papers you cited about these 2 ways and could not find any explicit and clear description. And I really don't know how to align 5 predicted finger tips to ground truth. Could u provide scripts about these 2 kinds of alignment?

Thanks.
Hao
