### ISSUE TITLE
run app.py TypeError: update_geometry(): incompatible function arguments

### ISSUE THREAD

**Issue by masommao** [CalciferZh/minimal-hand#70]
TypeError: update_geometry(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d.visualization.Visualizer) -> bool

**Comment by DonFlymoor** [comment]
I have the exact same problem.
Ubuntu 20.04
python 3.7.9
```bash
Traceback (most recent call last):
  File "app.py", line 121, in <module>
    live_application(OpenCVCapture())
  File "app.py", line 100, in live_application
    viewer.update_geometry(mesh)
TypeError: update_geometry(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d.visualization.Visualizer) -> bool

Invoked with: Visualizer with name Minimal Hand - output, geometry::TriangleMesh with 778 points and 1538 triangles.

```

**Comment by Techn0logic** [comment]
Running into exactly same issue.

Ubuntu 16.04
Python 3.7.0

`pip list 

Package              Version
-------------------- -------------------
absl-py              0.11.0
argon2-cffi          20.1.0
astor                0.8.1
async-generator      1.10
attrs                20.3.0
backcall             0.2.0
bleach               3.2.1
cached-property      1.5.2
certifi              2020.11.8
cffi                 1.14.4
chumpy               0.70
decorator            4.4.2
defusedxml           0.6.0
entrypoints          0.3
gast                 0.4.0
google-pasta         0.2.0
grpcio               1.34.0
h5py                 3.1.0
importlib-metadata   3.1.1
ipykernel            5.3.4
ipython              7.19.0
ipython-genutils     0.2.0
ipywidgets           7.5.1
jedi                 0.17.2
Jinja2               2.11.2
jsonschema           3.2.0
jupyter-client       6.1.7
jupyter-core         4.7.0
jupyterlab-pygments  0.1.2
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
keyboard             0.13.4
Markdown             3.3.3
MarkupSafe           1.1.1
mistune              0.8.4
mkl-fft              1.2.0
mkl-random           1.2.0
mkl-service          2.3.0
nbclient             0.5.1
nbconvert            6.0.7
nbformat             5.0.8
nest-asyncio         1.4.3
notebook             6.1.5
numpy                1.18.1
open3d               0.8.0.0
opencv-python        3.4.3.18
packaging            20.7
pandocfilters        1.4.3
parso                0.7.1
pexpect              4.8.0
pickleshare          0.7.5
pip                  20.1.1
prometheus-client    0.9.0
prompt-toolkit       3.0.8
protobuf             3.14.0
ptyprocess           0.6.0
pycparser            2.20
pygame               1.9.4
Pygments             2.7.2
pyparsing            2.4.7
pyrsistent           0.17.3
python-dateutil      2.8.1
pyzmq                20.0.0
scipy                1.5.4
Send2Trash           1.5.0
setuptools           49.6.0.post20201009
six                  1.15.0
tensorboard          1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       1.14.0
termcolor            1.1.0
terminado            0.9.1
testpath             0.4.4
tornado              6.1
traitlets            5.0.5
transforms3d         0.3.1
wcwidth              0.2.5
webencodings         0.5.1
Werkzeug             1.0.1
wheel                0.36.0
widgetsnbextension   3.5.1
wrapt                1.12.1
zipp                 3.4.0
`

**Comment by Techn0logic** [comment]
I found that updating open3d to 0.9 solves the issue.

```
pip install open3d==0.9
```

After updating the application starts.

**Comment by CalciferZh** [comment]
Many thanks @Techn0logic   I should update the requirements.
