### ISSUE TITLE
About the fitting effect of semanctic gesture

### ISSUE THREAD

**Issue by nsl2014fm** [CalciferZh/minimal-hand#71]
Hi， thanks for your great work.

In the demo, the fitting effect of semanctic gestures is poor, such that "ok"、“Number 3” or even “fist”.  I am confused with this phenomenon. **Is it due to lack of semantic gesture samples in training dataset?** The model connot fit the corresponding keypoints of gestures

**Comment by CalciferZh** [comment]
Hi, thanks for your interest.

The semantic gestures are the "outliers", or "unnatural", to some extent. In daily life, for most of the time, people don't use semantic gestures very much. Instead, the most frequent hand poses would be object interactions or the relaxing poses. As a result, the hand poses of in-the-wild images are always without any semantic meaning, while the hand-specific data intentionally recorded in the studio are usually with significant semantics meaning. This difference in distribution may make it difficult to handle both cases very well at the same time.

During training, we intentionally increase the ratio of in-the-wild training data, hoping for better robustness. This might make the model less biased to the semantic gestures.

**Comment by nsl2014fm** [comment]
got it, thx
