### ISSUE TITLE
How to compute quaternions between target hand pose and reference hand pose?

### ISSUE THREAD

**Issue by f6ra07nk14** [CalciferZh/minimal-hand#72]
I am interested in training IKNet.
Currently I am going to prepare this dataset for IKNet, 
but I was confused about "computing quaternions between target hand pose and reference hand pose".

Thanks in advance.

**Comment by CalciferZh** [comment]
> computing quaternions between target hand pose and reference hand pose

Could you provide more context on this sentence?

**Comment by f6ra07nk14** [comment]
What I know until now is that we can randomly generate hand shape with normal distribution, 
but I am not sure how to prepare the ground truth quaternions for hand pose (like MoCap Data in paper).

**Comment by CalciferZh** [comment]
I think such data can only be obtained by using some high-accuracy capture system.
