### ISSUE TITLE
How can I run app.py for video not for camera , I run in DGX-2 ,it have not Camera.

### ISSUE THREAD

**Issue by sungyihsun** [CalciferZh/minimal-hand#73]
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
2020-12-04 09:58:17.676114: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
[ WARN:0] global /tmp/pip-req-build-qacpj5ci/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[Open3D ERROR] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D ERROR] Failed to initialize GLFW
Traceback (most recent call last):
  File "app.py", line 122, in <module>
    live_application(OpenCVCapture())
  File "app.py", line 49, in live_application
    cam_params = view_control.convert_to_pinhole_camera_parameters()
AttributeError: 'NoneType' object has no attribute 'convert_to_pinhole_camera_parameters'

**Comment by CalciferZh** [comment]
> GLFW Error: X11: The DISPLAY environment variable is missing

Seems that you have some problem with display. I'm afraid I cannot help with this.
