### ISSUE TITLE
run app.py error!The input gesture is inconsistent with the output gesture, and the output jumps frequently what I should do？

### ISSUE THREAD

**Issue by masommao** [CalciferZh/minimal-hand#74]

**Comment by k2m5t2** [comment]
it might be that you are using the wrong hand - could you attach some screenshots?

**Comment by masommao** [comment]
hi all，Is there any result for the video I provided?Looking forward to you reply，thanks.
----- 原始邮件 -----
发件人：k2m5t2 <notifications@github.com>
收件人：CalciferZh/minimal-hand <minimal-hand@noreply.github.com>
抄送人：masommao <13823120727m0@sina.cn>,  Author <author@noreply.github.com>
主题：Re:_[CalciferZh/minimal-hand]_run_app.py_error!The_input_gesture_is_inconsistent_with_the_output_gesture,_and_the_output_jumps_frequently_what_I_should_do？_(#74)
日期：2020年12月09日 03点21分


it might be that you are using the wrong hand - could you attach some screenshots?

&mdash;

**Comment by CalciferZh** [comment]
I'll close this as it seems to be inactive.
