### ISSUE TITLE
about dexter+object and EgoDexter dataset

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#77]
Hi, I found some labels of DO and ED dataset are wrong, as some 2D projection of 3D annotations mismatch with suitable locations.
I abandoned the bad annotations and found great improvment especially in ED dataset, with AUC value  0.893 compared with your result 0.804.
What do u make of this?

**Comment by CalciferZh** [comment]
Thanks for the information. I was not aware of this when writing the paper. Maybe you can also inform the authors of the datasets.
