### ISSUE TITLE
about the augmentation of MoCap data

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#78]
Hi, I am curious about the augmentation of Mocap data.
For shape, u use normal distribution N (0,3). Why do u use  N (0,3)? Could it cover the most or full shape space of hand?
For pose, u base on 2 assumptions:"1.each finger's pose is independent; 2.any interpolation in quaternion space of MANO-related data is valid".I doubt that the first  hypothesis might not hold as they may crush or interpenetrate. And the interpolation might still be invalid.
What do u make of all this?

Thanks,
Hao

**Comment by CalciferZh** [comment]
For N(0,3), the std is empirically set. For the assumption, it's not perfect but works fine so far. Of course we would like to see some better constraints that take care of all the corner cases.
