### ISSUE TITLE
reimplementation of your paper

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/minimal-hand#79]
I reimplement some parts of your paper and that project is open source on https://github.com/MengHao666/Minimal-Hand-pytorch. It would be very kind of u if u can check it.Thanks

**Comment by CalciferZh** [comment]
Hi, many thanks to your effort! I have added a link to your repo.

P.S. maybe make sure it is legal to redistribute the datasets via BaiduDisk or Google Drive.

**Comment by MengHao666** [comment]
> Hi, many thanks to your effort! I have added a link to your repo.
> 
> P.S. maybe make sure it is legal to redistribute the datasets via BaiduDisk or Google Drive.

Thanks for the reminder, and I have revised it just now.
All the best.
