### ISSUE TITLE
Any plans on evaluating on FreiHAND dataset?

### ISSUE THREAD

**Issue by pablovela5620** [CalciferZh/minimal-hand#8]
I'm curious as it seems to be one of the better datasets publicly available, not only does it include really accurate 3D poses, but they are all on real images include challenging poses and object interactions. Along with all of this, it includes MANO hand shape ground truths. I would love to see how this model performs. 

It also allows for seeing how this performs without needing alignment since both camera intrinsics and scale are included for each image

I'm also curious if this would be a good alternative for training IKNet instead of the MoCap data since it includes the hand shape ground truths. I'm not sure if I should open a separate issue for that to make it easier for others to find

**Comment by CalciferZh** [comment]
Hi. we are currently working on incorporating FreiHand dataset. Hopefully we can update the model in one or two weeks. However, the preliminary results show that using FreiHand does not improve the results on other datasets significantly. Maybe that's because we have already utilized quite a few datasets.

We still believe that MoCap data is better for the IK part, since they are obtained from high quality scans.

Thank you so much for your suggestions and interest :)

**Comment by pablovela5620** [comment]
great would love to see how it does with the shape data instead of IK since it seems more easily available. Can't wait to see what results look like on the evaluation set of FreiHand

**Comment by liwenssss** [comment]
I notice that in the MoCap dataset, \theta \in R^{48}, how do you get the corresponding \theta \in R^{63} to fit your MANO model ?

**Comment by CalciferZh** [comment]
It's explained in the [supplementary document](thttps://calciferzh.github.io/files/zhou2020mocular_supp.pdf) Sec.3

**Comment by MengHao666** [comment]
> I'm curious as it seems to be one of the better datasets publicly available, not only does it include really accurate 3D poses, but they are all on real images include challenging poses and object interactions. Along with all of this, it includes MANO hand shape ground truths. I would love to see how this model performs.
> 
> It also allows for seeing how this performs without needing alignment since both camera intrinsics and scale are included for each image
> 
> I'm also curious if this would be a good alternative for training IKNet instead of the MoCap data since it includes the hand shape ground truths. I'm not sure if I should open a separate issue for that to make it easier for others to find

@pablovela5620 Hi, I am confused about the alignment method used in this paper.Do u know how to implement such alignment?
