### ISSUE TITLE
Full Body?

### ISSUE THREAD

**Issue by Adeel-Intizar** [CalciferZh/minimal-hand#81]
Hello, Thank you for your great work
How to run this implementation on full body?
Thank you

**Comment by CalciferZh** [comment]
Hi, I think you need to first use some third party hand detector to localize the hand, crop that area from the original image, and then feed in to the model.

**Comment by Adeel-Intizar** [comment]
I am not talking about hand, what about full body ?

**Comment by CalciferZh** [comment]
I'm afraid that's not possible.
