### ISSUE TITLE
what is the python version?

### ISSUE THREAD

**Issue by not-william** [CalciferZh/minimal-hand#87]
Hello,

What python version is required to run this repository?

I have tried 3.9 and the dependencies don't install - `ERROR: No matching distribution found for pygame==1.9.4`.

Thanks

**Comment by sidoodler** [comment]
Hi, I am running this repository with python==3.6.12 and pygame==2.0.1. You can try these versions and see if they work for you.

**Comment by CalciferZh** [comment]
Many thanks for @sidoodler 's reply

**Comment by amundra15** [comment]
Hi @sidoodler, were you able to set up the repo with this python version?
