### ISSUE TITLE
Python environment

### ISSUE THREAD

**Issue by dnorambu** [CalciferZh/minimal-hand#94]
Hi, what's the propper python version to install dependencies and run the project? I've been trying with 3.6.3, 3.6.8, 3.7.8, 3.9.10 but always get stucked installing dependencies (open3d, tensorflow, pygame). Thanks in advance :)

**Comment by dnorambu** [comment]
Nevermind, i was using 32-bit version of python :v Mb. With python 3.6.8 works fine, although I saw an error related to pywinpty package (pip version 21.3.1)

![imagen](https://user-images.githubusercontent.com/65257235/155003932-3e796d24-5818-4a98-818e-d7139ffec0bc.png)

**Comment by CalciferZh** [comment]
Sorry but I'm afraid I cannot help with it. I'm not an expert in packages and environments.

**Comment by dnorambu** [comment]
@CalciferZh Don't worry :) ty for the reply
