### ISSUE TITLE
delta = delta * length为什么要进行相乘操作呢？

### ISSUE THREAD

**Issue by tonylin52** [CalciferZh/minimal-hand#95]
你好，在wrappers.py文件166行，使用delta = delta * length 作为ikmodel的输入之一 方便问一下这么做的原因吗？
delta是关节归一化向量，乘以关节长度是为什么呢？

我理解输入到后面ik模型的参数 需要有手部mesh模板参数，手部姿态参数sita（delta），skinning weights，手部坐标参数（xyz）

所以就比较困惑只输入delta就可以了，为什么要相乘一下length。。。。

**Comment by tonylin52** [comment]
另外self.mpii_ref_xyz, self.mpii_ref_delta 这两个参数都是固定的，为什么还要都输入到网络中呢，省略掉会不会更好一些

**Comment by CalciferZh** [comment]
当初设计的本意是提供给网络关于手部尺寸的信息，但是确实没有仔细验证过是不是有效。

**Comment by tonylin52** [comment]
> 

谢谢！ 另外方便问一下 iknet的训练集是如何收集的吗？我最近在做手势识别相关研究，这面想跟您讨论一下

**Comment by CalciferZh** [comment]
论文里面有详细说明的

**Comment by tonylin52** [comment]
论文中有说明 MoCap数据集，但是没有相关标注与说明是图和获得的
